profile:
  username: "default"
  email: "" 

samba:
  shares:
    - name: "Media"
      directory: /DATA/Media
      user: chirag
      group: smbmedia
      browseable: "yes"
      writable: "no"

applications:
  homelab-dashboard:
    enable: true
    username: admin
    password: default-password
    secret_key: default-secret
    data_path: "/DATA/AppData/homelab-dashboard/data"

  plex-server: 
    enable: true
    base_url: "http://192.168.0.160"
    plex_claim: "<plex-claim>"
    config_path: "/DATA/AppData/plex/config"
    transcode_path: "/DATA/AppData/plex/transcode"
    media_path: "/DATA/Media"

  portainer: 
    enable: true
    base_url: "http://192.168.0.160"
    config_path: "/DATA/AppData/portainer"

  transmission: 
    enable: true
    base_url: "http://192.168.0.160"
    username: admin
    password: default-password 
    config_path: "/DATA/AppData/transmission/config"
    downloads_path: "/DATA/Downloads/Torrent"
    watch_path: "/DATA/Downloads/Torrent/watch"

  vscode:
    enable: true
    base_url: "http://192.168.0.160"
    password: default-password
    directories:
      - name: "data"
        path: "/DATA/"
