# All the default Homelab aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/homelab/default/bash/rc

# Add your own exports, aliases, and functions here.
source ~/.local/share/homelab/bin/homelab_autocomplete

export HOMELAB_CONFIG=~/.local/share/homelab/config.yaml
export PATH="$PATH:/opt/nvim/bin"
alias vim="nvim"
bind '"\C-f": "~/.local/share/homelab/bin/tmux-sessionizer\n"'

alias yt-dlp-pl='yt-dlp -f b -o "%(playlist_index)s - %(title)s.%(ext)s" --playlist-items 1- '
alias docker="sudo docker"
