# All the default Homelab aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/homelab/default/bash/rc

# Add your own exports, aliases, and functions here.

export PATH="$PATH:/opt/nvim-linux64/bin"
alias vim="nvim"
bind '"\C-f": "~/.local/share/homelab/bin/tmux-sessionizer\n"'

# Configuration for NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias yt-dlp-pl='yt-dlp -f b -o "%(playlist_index)s - %(title)s.%(ext)s" --playlist-items 1- '
