name: dns-server

networks:
  dns_server_net:
    driver: bridge

services:
  dns-server:
    hostname: dns-server
    image: chiragsoni812/bind9-server
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "127.0.0.1:953:953/tcp"
    
    restart: always
    volumes:
      # Your named.conf, zone files, etc.
      - {{ .config_path }}:/etc/bind

      # Persist DNS dynamic data, journal files, etc.
      - {{ .data_path }}:/var/cache/bind

      # Log files
      - {{ .log_path }}:/var/log/bind
    
    networks:
      - dns_server_net

    # Optional: increase file limit (Bind loads zones at startup)
    ulimits:
      nofile: 4096
