name: dns-server

services:
  dns-server:
    hostname: dns-server
    image: chiragsoni812/bind9-server
    network_mode: host
    
    restart: always
    volumes:
      # Your named.conf, zone files, etc.
      - {{ .config_path }}:/etc/bind

      # Persist DNS dynamic data, journal files, etc.
      - {{ .data_path }}:/var/cache/bind

      # Log files
      - {{ .log_path }}:/var/log/bind
    
    # Optional: increase file limit (Bind loads zones at startup)
    ulimits:
      nofile: 4096
