name: portainer

networks:
  portainer_net:
    driver: bridge

services:
  portainer:
    hostname: portainer
    image: portainer/portainer-ce:2.21.1
    labels:
      - "x-homelab=ture"
      - "x-homelab-name=portainer"
      - "x-homelab-web-url={{ .base_url }}:9000/"
      - "x-homelab-icon=https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Portainer/icon.png"
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
      - target: 9000
        published: "9000"
        protocol: tcp
      - target: 9443
        published: "9443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      {{ if .config_path }}
      - type: bind
        source: {{ .config_path }}
        target: /data
      {{ end }}
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - portainer_net
    privileged: false
