name: transmission

networks:
  transmission_net:
    driver: bridge

services:
  transmission:
    hostname: transmission
    container_name: transmission
    environment:
      - PEERPORT=51413
      - PGID=1000
      - PUID=1000
      - USER={{ .username }}
      - PASS={{ .password }}
      - TZ=Asia/Kolkata
    image: linuxserver/transmission:4.0.4
    labels:
      - "x-homelab=true"
      - "x-homelab-index=3"
      - "x-homelab-name=transmission"
      - "x-homelab-web-url={{ .base_url }}:9091/"
      - "x-homelab-icon=https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Transmission/icon.png"
    ports:
      - target: 9091
        published: "9091"
        protocol: tcp
      - target: 51413
        published: "51413"
        protocol: tcp
      - target: 51413
        published: "51413"
        protocol: UDP
    restart: unless-stopped
    volumes:
      {{ if .config_path }}
      - type: bind
        source: {{ .config_path }}
        target: /config
      {{ end }}
      {{ if .downloads_path }}
      - type: bind
        source: {{ .downloads_path }}
        target: /downloads
      {{ end }}
      {{ if .watch_path }}
      - type: bind
        source: {{ .watch_path }}
        target: /watch
      {{ end }}
    networks:
      - transmission_net
    privileged: false
