name: vscode

networks:
  vscode_net:
    driver: bridge

services:
  vscode:
    environment:
      - PASSWORD={{ .password }}
      - PORT=8080
    hostname: vscode
    image: chiragsoni812/self-hosted-vscode:latest
    labels:
      - "x-homelab=true"
      - "x-homelab-index=3"
      - "x-homelab-name=vscode"
      - "x-homelab-web-url={{ .base_url }}:8088/"
      - "x-homelab-icon=https://code.visualstudio.com/assets/images/code-stable.png"
    ports:
      - target: 8080
        published: "8088"
        protocol: tcp
    restart: unless-stopped
    volumes:
      {{ range $i, $v := .directories }}
      - type: bind
        source: {{ $v.path }} 
        target: /root/{{ $v.name }}
      {{ end }}
    networks:
      - vscode_net
    privileged: false
