name: web-nvim

networks:
  web_nvim_net:
    driver: bridge

services:
  web-nvim:
    hostname: web-nvim
    container_name: web-nvim
    environment:
      - GOTTY_CREDENTIAL={{ .username }}:{{ .password }}
      - GOTTY_PORT=8080

    image: chiragsoni812/web-nvim:latest
    {{ if and .uid .gid }}
    user: "{{ .uid }}:{{ .gid }}"
    {{ end }}
    labels:
      - "x-homelab=true"
      - "x-homelab-index=4"
      - "x-homelab-name=nvim"
      - "x-homelab-web-url={{ .base_url }}"
      - "x-homelab-icon=https://avatars.githubusercontent.com/u/6471485"
    ports:
      - target: 8080
        published: "8088"
        protocol: tcp
    restart: unless-stopped
    volumes:
      {{ range $i, $v := .user_directories }}
      - type: bind
        source: {{ $v.path }}
        {{ if and $.uid $.gid }}
        target: /home/ubuntu/code/{{ $v.name }}
        {{ else }}
        target: /root/code/{{ $v.name }}
        {{ end }}
      {{ end }}
      {{ if .ssh_directory }}
      - type: bind
        source: {{ .ssh_directory }} 
        {{ if and .uid .gid }}
        target: /home/ubuntu/.ssh
        {{ else }}
        target: /root/.ssh
        {{ end }}
      {{ end }}
    networks:
      - web_nvim_net
    privileged: false
