name: web-nvim

networks:
  web_nvim_net:
    driver: bridge

services:
  web-nvim:
    hostname: web-nvim
    container_name: web-nvim
    environment:
      - GOTTY_CREDENTIAL={{ .username }}:{{ .password }}
      - GOTTY_PORT=8080

    image: chiragsoni812/web-nvim:latest
    labels:
      - "x-homelab=true"
      - "x-homelab-index=3"
      - "x-homelab-name=nvim"
      - "x-homelab-web-url={{ .base_url }}:8088/"
      - "x-homelab-icon=https://icons.iconarchive.com/icons/papirus-team/papirus-apps/256/nvim-icon.png"
    ports:
      - target: 8080
        published: "8088"
        protocol: tcp
    restart: unless-stopped
    volumes:
      {{ range $i, $v := .user_directories }}
      - type: bind
        source: {{ $v.path }} 
        target: /root/code/{{ $v.name }}
      {{ end }}
      {{ if .ssh_directory }}
      - type: bind
        source: {{ .ssh_directory }} 
        target: /root/.ssh
      {{ end }}
    networks:
      - web_nvim_net
    privileged: false
