#!/bin/bash
set -euo pipefail

RECREATE=false
APPLICATION_NAME=""
APPLICATION_FOUND="false"

for arg in "$@"; do
  case "$arg" in
    --recreate)
      RECREATE=true
      shift || true
      ;;
    --application)
      shift || true
      APPLICATION_NAME="$@"
      ;;
    *)
      ;;
  esac
done

COMPOSE_BASE_DIR="$HOME/.local/share/homelab/applications"

# Loop through each application in config
yq -r '.applications | to_entries[] | "\(.key) \(.value.enable)"' "$HOMELAB_CONFIG" | \
while read -r app enable_status; do
    if [[ "$APPLICATION_NAME" == "" || "$APPLICATION_NAME" == "$app" ]]; then
        APPLICATION_FOUND="true"
    else
        continue
    fi

    compose_template="$COMPOSE_BASE_DIR/$app.yaml"

    RENDERED_APPLICATIONS_DIR="$COMPOSE_BASE_DIR/.current"
    if [[ ! -d "$COMPOSE_BASE_DIR/.current" ]]; then
        mkdir $RENDERED_APPLICATIONS_DIR
    fi
    compose_file="$RENDERED_APPLICATIONS_DIR/$app.yaml"



    # Skip if template file not found
    if [[ ! -f "$compose_template" ]]; then
        echo "!!! Template file for $app not found, skipping."
        continue
    fi

    if [[ "$enable_status" == "true" ]]; then
        echo ">>> Enabling: $app"

        # Copy template to target file
        cp "$compose_template" "$compose_file"

        # Rendering compose files from the go template engine
        APP_CONFIGURATIONS=$(yq -o json ".applications[\"$app\"]" "$HOMELAB_CONFIG")
        echo $APP_CONFIGURATIONS | tpl -f $compose_template > $compose_file

        if [[ "$RECREATE" == true ]]; then
            sudo docker compose -f "$compose_file" down
            sudo docker compose -f "$compose_file" pull
            sudo docker compose -f "$compose_file" up -d
        else
            sudo docker compose -f "$compose_file" pull
            sudo docker compose -f "$compose_file" up -d
        fi
        echo "*** Enabled: $app"
    else
        echo ">>> Disabling: $app"
        sudo docker compose -f "$compose_file" down
        echo "*** Disabled: $app"
    fi
done

if [[ "$APPLICATION_FOUND" == "false" ]]; then
    echo "No application exists with name $APPLICATION_NAME"
fi
